-- zlt_vid_info
  CREATE TABLE "SALE"."ZLT_VID_INFO" 
   (	"ID_KEY" NUMBER(20,0) NOT NULL ENABLE, 
	"Z_VID_NAME" VARCHAR2(100 BYTE), 
	"Z_VID_URL" VARCHAR2(256 BYTE), 
	"Z_UPLOAD_DATE" DATE, 
	"Z_UPLOADER_ID" NUMBER(20,0), 
	"Z_UPLOADER_NM" VARCHAR2(20 BYTE), 
	"Z_VID_MD5" VARCHAR2(100 BYTE), 
	"Z_VID_UPLOADED" NUMBER(1,0), 
	 CONSTRAINT "ZLT_VID_INFO_PK" PRIMARY KEY ("ID_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SALE"."ZLT_VID_INFO"."ID_KEY" IS '主键';
   COMMENT ON COLUMN "SALE"."ZLT_VID_INFO"."Z_VID_NAME" IS '视频名称';
   COMMENT ON COLUMN "SALE"."ZLT_VID_INFO"."Z_VID_URL" IS '视频路径';
   COMMENT ON COLUMN "SALE"."ZLT_VID_INFO"."Z_UPLOAD_DATE" IS '上传时间';
   COMMENT ON COLUMN "SALE"."ZLT_VID_INFO"."Z_UPLOADER_ID" IS '上传人ID';
   COMMENT ON COLUMN "SALE"."ZLT_VID_INFO"."Z_UPLOADER_NM" IS '上传人';
   COMMENT ON COLUMN "SALE"."ZLT_VID_INFO"."Z_VID_MD5" IS '视频MD5值';
   COMMENT ON COLUMN "SALE"."ZLT_VID_INFO"."Z_VID_UPLOADED" IS '是否上传完毕?1:已完毕;0:未完毕';


--  zlt_vid_info_l
  CREATE TABLE "SALE"."ZLT_VID_INFO_L" 
   (	"ID_KEY" NUMBER(20,0) NOT NULL ENABLE, 
	"Z_VID_CHUNK" NUMBER(5,0), 
	"Z_VID_MD5" VARCHAR2(100 BYTE), 
	"Z_VID_CHUNKS" NUMBER(5,0), 
	 CONSTRAINT "ZLT_VID_INFO_L_PK" PRIMARY KEY ("ID_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "SALE"."ZLT_VID_INFO_L"."ID_KEY" IS '主键';
   COMMENT ON COLUMN "SALE"."ZLT_VID_INFO_L"."Z_VID_CHUNK" IS '当前切片数';
   COMMENT ON COLUMN "SALE"."ZLT_VID_INFO_L"."Z_VID_MD5" IS '视频MD5值';
   COMMENT ON COLUMN "SALE"."ZLT_VID_INFO_L"."Z_VID_CHUNKS" IS '总切片数';




-- 视图
  CREATE OR REPLACE FORCE VIEW "SALE"."ZLTV_VID_UPLOADING" ("ID_KEY", "Z_VID_NAME", "Z_UPLOAD_DATE", "Z_UPLOADER_ID", "Z_UPLOADER_NM", "Z_VID_MD5", "Z_VID_UPLOADED", "Z_UPLOADED_CHUNKS", "Z_VID_CHUNKS", "Z_UPLOAD_PROGRESS") AS 
  select a.id_key, a.z_vid_name, a.z_upload_date, a.z_uploader_id, z_uploader_nm, a.z_vid_md5, a.z_vid_uploaded,
b.z_uploaded_chunks,b.z_vid_chunks,
to_char(ROUND((b.z_uploaded_chunks/b.z_vid_chunks),2)*100,'99D99')||'%' z_upload_progress
from zlt_vid_info a
left outer join 
(select z_vid_chunks,z_vid_md5,count(1) z_uploaded_chunks from zlt_vid_info_l group by z_vid_chunks,z_vid_md5 ) b
on a.z_vid_md5 = b.z_vid_md5 
where a.z_vid_uploaded = 0;

   COMMENT ON COLUMN "SALE"."ZLTV_VID_UPLOADING"."ID_KEY" IS '主键';
   COMMENT ON COLUMN "SALE"."ZLTV_VID_UPLOADING"."Z_VID_NAME" IS '视频名称';
   COMMENT ON COLUMN "SALE"."ZLTV_VID_UPLOADING"."Z_UPLOAD_DATE" IS '上传时间';
   COMMENT ON COLUMN "SALE"."ZLTV_VID_UPLOADING"."Z_UPLOADER_ID" IS '上传人ID';
   COMMENT ON COLUMN "SALE"."ZLTV_VID_UPLOADING"."Z_UPLOADER_NM" IS '上传人';
   COMMENT ON COLUMN "SALE"."ZLTV_VID_UPLOADING"."Z_VID_MD5" IS '视频MD5值';
   COMMENT ON COLUMN "SALE"."ZLTV_VID_UPLOADING"."Z_VID_UPLOADED" IS '是否上传完毕?0:未完毕;1:已完毕';
   COMMENT ON COLUMN "SALE"."ZLTV_VID_UPLOADING"."Z_UPLOADED_CHUNKS" IS '已上传切片数';
   COMMENT ON COLUMN "SALE"."ZLTV_VID_UPLOADING"."Z_VID_CHUNKS" IS '该视频总切片数';
   COMMENT ON COLUMN "SALE"."ZLTV_VID_UPLOADING"."Z_UPLOAD_PROGRESS" IS '上传进度';
